# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'



menu:
- {name: 'Conócenos', folder: 'pages', file: 'conócenos.html'}
- {name: 'Casos Médicos', folder: 'pages', file: 'casos-médicos.html'}
- {name: 'Entregables', folder: 'pages', file: 'entregables.html'}
- {name: 'Modelos', folder: 'pages', file: 'modelos.html'}
- {name: 'Bibliografía', folder: 'pages', file: 'bibliografía.html'}



# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'No te olvides de compartir esta información!'

related_posts: 'También te puede interesar...'

post_date_prefix: 'Escribe en'
